Add Tilt support for legacy grids
monome/norns pull request #1477
Opened 2021-12-05 00:18 UTC by okyeron

Adds support for tilt.

Tested on norns shield and a grayscale 64 (2010-2012) - serial m64-0993  
grid presents as `grid monome 64 m64-0993 8x8`

For testing I added tilt to my grid-test script in this branch: https://github.com/okyeron/grid-test/tree/tilt
(tilt can be enabled/disabled in the params menu)

Results:	 
* X/Y data comes through, no Z (although no Z data was observed on Max test-grid patch either).
* Values displayed are between ~90 and ~170, with ~130 in the center (grid flat on table)

Questions:  
* Is there no Z on that grid model? Is there Z on others?
* What are expected values? Seems like 0 to <200 when testing with the Max test-grid patch

2021-12-05 00:32 UTC, ngwese commented
One quick note, this PR appears to include what appear to be unrelated updates to the `softcut` and `link` submodules. It is preferable to have the submodules remain the as is (admittedly we haven't done a great job of that in the past.)

2021-12-05 02:18 UTC, okyeron commented
Apologies, I noticed the softcut/link items after the fact.

I'm not entirely sure what I did that made those include here - aside from doing `git submodule update --init --recursive` on the source from the current norns head prior to making these changes.

Is there a good way to remove those references from this PR?

2021-12-05 04:31 UTC, ngwese commented
I think you can checkout the previous commits for the `softcut` and `link` modules then `git add` those modules and `git commit --amend`. You likely need to `git push --force` to this PR branch as Github will likely complain because your local and this remote branch will have diverged as a result of using `--amend`.

The result should be a single commit which no longer shows the submodule changes.

2021-12-05 22:10 UTC, tehn requested changes
this is great, thank you!

i totally don't remember designing the tilt protocol for multiple sensors... had to dig back

2021-12-05 22:10 UTC, tehn commented on matron/src/device/device_monome.c
> +    ev->grid_tilt.z = e->tilt.y;
typo here? tilt.y repeated

2021-12-06 01:20 UTC, tehn approved these changes

2021-12-06 01:21 UTC, merged